server:
  port: 8080

zuul:
  routes:
    users:
      path: /myusers/**
      url: http://scooterlabs.com/echo/
      
ribbon.eureka.enabled: false

security:
  basic:
    enabled: false
  sessions: stateless

oauth:
  clientId: 887174581528-jup6nprs4kv7qdnjmk0i3mh3b38ui4qn.apps.googleusercontent.com
  clientSecret: V3c8pP9_5pmRhVfP2oy4DNdP
  checkTokenUrl: https://www.googleapis.com/oauth2/v3/tokeninfo?access_token={accessToken}
  userInfoUrl: https://www.googleapis.com/userinfo/v2/me
  signingKey: MaYzkSjmkzPC57L
  
      
    
    
    