server:
  port: 9997
  
ribbon.eureka.enabled: false

management.security.enabled: false

security:
  basic:
    enabled: false
  sessions: stateless
  
---
spring:
    profiles: loc
zuul:
  routes:
    traint:
      path: /api/tramits/**
      url: http://localhost:8700/api/tramits/
      
---
spring:
    profiles: dev
zuul:
  routes:
    traint:
      path: /api/tramits/**
      url: http://localhost:8082/gsittraint-service/api/tramits/
      
---
spring:
    profiles: conso
zuul:
  routes:
    traint:
      path: /api/tramits/**
      url: http://ctti12/gsittraint-service/api/tramits/